export const FETCH_CAMERAS_REQUEST = 'FETCH_CAMERAS_REQUEST';
export const FETCH_CAMERAS_SUCCESS = 'FETCH_CAMERAS_SUCCESS';
export const FETCH_CAMERAS_ERROR = 'FETCH_CAMERAS_ERROR';

export const FETCH_ONECAMERA_REQUEST = 'FETCH_ONECAMERA_REQUEST';
export const FETCH_ONECAMERA_SUCCESS = 'FETCH_ONECAMERA_SUCCESS';
export const FETCH_ONECAMERA_ERROR = 'FETCH_ONECAMERA_ERROR';

export const ADD_CAMERA_REQUEST = 'ADD_CAMERA_REQUEST';
export const ADD_CAMERA_SUCCESS = 'ADD_CAMERA_SUCCESS';
export const ADD_CAMERA_ERROR = 'ADD_CAMERA_ERROR';